### PR TITLE
fix(mf-parser): provide getInfo advanced typings

### PR DESCRIPTION
**Pull request by tpoisseau**
rework of https://github.com/cheminfo/mass-tools/pull/231

### CODE REVIEW

**Comment by tpoisseau** [comment]
Any idea why locally I have this error in my tests:

```
⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯

 FAIL  packages/isotopic-distribution/src/__tests__/isotopicDistribution.test.js > test isotopicDistribution > extreme case with very few points
AssertionError: expected NaN to be close to 12010735.5, received difference is NaN, but expected 0.005
 ❯ packages/isotopic-distribution/src/__tests__/isotopicDistribution.test.js:396:26
    394|     });
    395| 
    396|     expect(profile.x[0]).toBeCloseTo(12010735.5);
       |                          ^
    397|     expect(profile.y[0]).toBeCloseTo(100);
    398|   });

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯
```

But not in CI ?

**Comment by targos** [comment]
I would use `fix` for the commit message because it has effect on TS users, not only documentation (and `docs` prefix doesn't trigger a new release-please pull request)

**Comment by targos** [comment]
I don't have the error locally. Did you run `npm test` or something else?

**Review by lpatiny — COMMENTED** [review]
I'm not able to judge TS migration anyway but I plan to simplify the library (and make breaking changes) to avoid custom name for properties among other. Don't hesitate to create issues if you see    some complex pattern.

**Comment by stropitek** [comment]
Ref: https://github.com/cheminfo/mass-tools/issues/234

**Comment by tpoisseau** [comment]
> I don't have the error locally. Did you run npm test or something else?

It happen with `npm test` and `npm run test-only`

**Review by targos — APPROVED** [review]
Difficult to review TS change impact but LGTM based on updated test.

**Comment by tpoisseau** [comment]
Refs: https://github.com/cheminfo/mass-tools/issues/226

**Comment by targos** [comment]
Maybe we don't have the same dependency tree, but this is weird.

**Comment by tpoisseau** [comment]
@lpatiny

Typescript is very rich in its ability to define and express types, but if we can use simple types and avoid dynamic properties in the future, I'd be very grateful ^^.

In terms of suggestions, I'd say strongly type all the inputs and outputs of each function. I went down the rabbit hole on my previous PR https://github.com/cheminfo/mass-tools/pull/231. I had a lot of trouble typing `MFParsedPart` and `ToPartsPart`. Properties should not be added dynamically, and mutations should be avoided as much as possible. I also recommend defining all discriminated types rather than one type that would be the approximate fusion of all possibilities.

I think you'll find this abandoned RP useful for examples of precisely defined types.

**Pull request merged**
