### PR TITLE
esm

### PR DESCRIPTION
**Pull request by lpatiny**
- wip: refactor to esm
- chore: remove lib
- wip: refactoring to esm module
- wip: migrate to esm
- chore: update peptide to esm
- chore: update nucleotide to esm
- refactor: esm of mf-parser
- chore!: refactor esm and remove default export
- chore!: migrate to esm and remove default export from package
- chore!: migrate to esm and remove default export
- chore!: update to esm and only expose msemMatcher and generalMatcher
- chore: working on esm migration
- chore!: migrate to esm and remove default export
- chore!: migrate to esm and remove default export
- wip: migrate emdb
- wip: migrate ms-preport
- wip: upgrate ms-spectrum to esm
- chore!: update chemical-elements to esm
- chore!: update chemical-groups to esm
- wip: update mf-generator to esm
- chore!: update mf-utilities to esm
- wip: update various files
- chore!: convert mf-generator to esm and remove default export
- chore!: migrate to esm and remove default export
- wip: migration of emdb to esm and expose EMDB (and not DBManaer)
- wip: migration of emdb to esm and expose EMDB (and not DBManaer)
- chore: migrate to esm. Should not be breaking.
- chore!: migrate to esm and remove Spectrum.JsGraph
- chore!: migrate to esm and remove IsotopicDistribution and MFParser. You should use mass-tools to have those 2 librairies
- chore!: migrate to esm and expose different variables
- chore(mf-parser): finish esm migration
- chore(emdb): finish esm migration and remove MFParser and IsotopicDistribution tests
- chore(nucleotide): finalize esm migration
- chore: various fix after esm migration

### CODE REVIEW

**Comment by targos** [comment]
Did you intend to push the `docs` folder?

**Comment by lpatiny** [comment]
> Did you intend to push the `docs` folder?

For now yes because I don't have a good solution to build it. I should create a custom github actions but I'm not sure it is trivial.

**Comment by targos** [comment]
> > Did you intend to push the `docs` folder?
> 
> For now yes because I don't have a good solution to build it. I should create a custom github actions but I'm not sure it is trivial.

How do you build it?

**Comment by lpatiny** [comment]
I use this command.

https://github.com/cheminfo/mass-tools/blob/master/package.json#L13

But really not perfect because the home page is even not generated automatically and lack most of the packages... https://cheminfo.github.io/mass-tools/

We will discuss tomorrow about it. There should be a better solution.

**Pull request merged**
